### ISSUE TITLE
FHIR-related code 

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/loinc2hpo#135]
It seems as if the FHIR-related code in the library does a lot of different things, but it might be good to offer just a simpler functionality for the library moving forward. Essentially, the core function is to take a FHIR Observation, extract the LOINC code and result, and return the annotation HPO code. The remaining functionality should be provide by application code that uses this library. That is, I would remove code such as FHIR retrieved.

The code Loinc2HPO library will have only one function in the API

public Optional<Hpo2Outcome> query(TermId loincId, Outcome outcome);

The FHIR library should have something like

public Optional<Hpo2Outcome> query(Observation);

Internally, this function needs to extract the loinc ID and code the outcome. All of the rest should be in application code.

Do we need anything else? Thoughts? @kingmanzhang @iimpulse

**Comment by kingmanzhang** [comment]
Agreed. The demo of FHIR transformation was an important part in the early stage for the demonstration of this project but not suitable to be together with this library. 

Also keep in mind that Amy has ported some of the methods for FHIR -> HPO in a separate library.

**Comment by pnrobinson** [comment]
Simplified with https://github.com/monarch-initiative/loinc2hpo/pull/140
