### ISSUE TITLE
consider ways to interpret N-to-1 mappings

### ISSUE THREAD

**Issue by kingmanzhang** [monarch-initiative/loinc2hpo#17]
There are two situations, 1) various tests with different accuracy for one phenotype 2) multiple time points for one phenotype (glucose tolerance test). Maybe using probabilities? e.g. 1.0 for yes/no tests, 1.0/N if there are N tests for one phenotype?

**Comment by pnrobinson** [comment]
For some of the tests there are more detailed interpretations, and in many cases one will order follow up tests to confirm a finding. It will not be possible to achieve 100% accuracy with mapping LOINC codes to what the patient "truly" had. I would suggest for the first approach that if one or more test of an N-to-1 mapping is abnormal, then the abnormal HPO code should be called. But let's keep this in mind!
