### ISSUE TITLE
blood values

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/loinc2hpo#2]
http://www.lymphomation.org/peripheral-blood-ref.pdf

**Comment by kingmanzhang** [comment]
I found a (book)[http://nurseselftraining.com/wp-content/books/242318509-Mosby-s-Manual-of-Diagnostic-and-Laboratory-Tests-5th-Edition-epub.pdf] for nurses that are quite helpful. We certainly do not need to manually curate all references, I anticipate it might be easier to use manually curated references than trying to parse FHIR reference range. An example is the coma score, the variations used by hospitals IT persons will make it harder to use than using our own (I assume the reference will be universal for most cases). Anyway, I suggest we buy the book if we find it really helpful during curation.

**Comment by pnrobinson** [comment]
Stale, we are not including our own set of reference values but expecting to get them from FHIR etc.
