### ISSUE TITLE
hpoListView

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/loinc2hpo#58]
In AnnotateTabController
```
    // TODO currently, this list is taking both HPO_CLass_Found and String at different parts of the app.
    @FXML private ListView hpoListView;
```
We should have a list take only one data type, and the type should always be declared. I tried this
```
 @FXML private ListView<HPO_Class_Found> hpoListView;
```
But there is one place in the code where the list is being initialized with a String.

**Comment by kingmanzhang** [comment]
This has been addressed.
